stitch:
  grant_type: client_credentials
  client-id: test-0bc5a12d-de6c-4b2f-b4c1-f0bab8246016
  client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
  audience: https://secure.stitch.money/connect/token
  scope: client_paymentrequest client_refund client_paymentauthorizationrequest
  base-url: https://secure.stitch.money/connect/token
  token-grant-type: authorization_code
  graph-ql: https://api.stitch.money/graphql
  initiate-payment-redirect-uri: https://8eb7-41-80-112-46.in.ngrok.io/user-payment-confirmations
  webhook-instant-pay: https://8eb7-41-80-112-46.in.ngrok.io/instantpay-notifications
  webhook-secret: 5b50d80c7dc7ae8bb1b1433cc0b99ecd2ac8397a555c6f75cb8a619ae35a0c35
  linkpay-redirect-uri: https://8eb7-41-80-112-46.in.ngrok.io/linkpay-authorizations
  response_type: code
   
server:
  port: 9090
  
logging:
  level:
    org:
      apache:
        http: DEBUG
      springframework:
        security: DEBUG    	
spring:
 h2:
  console:
    enabled: true
    path: /h2-console
 datasource:
    url: jdbc:h2:mem:stitch_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
 jpa:
   database-platform: org.hibernate.dialect.H2Dialect
 security:
    oauth2:
      client:
        registration:
          stitch:
            client-id: test-0bc5a12d-de6c-4b2f-b4c1-f0bab8246016
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "https://8eb7-41-80-112-46.in.ngrok.io/user-tokens"
            scope: openid,offline_access,accounts,transactions,balances,accountholders,paymentinitiationrequest
        provider:
          stitch:
            authorization-uri: https://secure.stitch.money/connect/authorize
            token-uri: https://secure.stitch.money/connect/token    